services:
  db:
    image: postgres:16
    container_name: saas_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=saas_db
      - POSTGRES_USER=saadmin
      - POSTGRES_PASSWORD=(password!)
    ports:
      - "5435:5432" # El puerto 5435 es para que tÃº entres desde afuera si quieres

  backend:
    build: ./backend
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=saas_db
      - DB_USER=saadmin
      - DB_PASS=(password!)
      - DB_HOST=db # Nombre del servicio de arriba
      - DB_PORT=5432
    depends_on:
      - db

  frontend:
    build: ./frontend
    user: "${DOCKER_USER:-}"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true

volumes:
  postgres_data:
  next_data: